# -*- coding: utf-8 -*-
"""Trabajo01_IA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IicEWfNKsyflR9TfcIMXBYx2ABt21gGF
"""

import math
from time import sleep


def f(s):
    s.sort()
    if len(s) > 3:
        a = s[0] + s[-1] + min(2 * s[1], s[0] + s[-2])
        return a + f(s[:-2])
    else:
        return sum(s[len(s) == 2:])


def evaluate(right, left, toMove):
    cost = max(toMove)
    right.extend(toMove)
    left = [_ for _ in left if _ not in toMove]
    returnCost = min(right)
    right.remove(returnCost)
    left.append(returnCost)
    rSum = sum(left)
    totalValue = cost + returnCost + rSum
    return totalValue, right, left, (cost + returnCost), [returnCost]


def hillClimbing(persons, movement, paint, changeText, right=[], left=[], total=0):
    if len(left) == 0:
        left = persons[:]
    left.sort()
    toMove = []
    minValue = math.inf
    currentCost = 0
    toReturn = []

    if len(left) == 2:
        toMove = left
        cost = max(left)
        right.extend(left)
        nLeft = []
        nRight = right
        currentCost = cost
        minValue = currentCost

        changeText("value", minValue)
        paint(toMove, "blue")

        changeText("value", 0)
        paint(toMove, "white")

    else:
        for a in left:
            _ = left[:]
            _.remove(a)
            for b in _:
                totalValue, cRight, cLeft, totalCost, cReturn = evaluate(right[:], left[:], [a, b])

                changeText("value", totalValue)
                paint([a, b], "blue")

                if (totalValue < minValue):
                    minValue = totalValue
                    toMove = [a, b]
                    nRight = cRight
                    nLeft = cLeft
                    currentCost = totalCost
                    toReturn = cReturn

                changeText("value", 0)
                paint([a, b], "white")

    print("______MOVE______")
    print(minValue)
    print(toMove)
    print(nRight)
    print(nLeft)
    print("Return: ", toReturn)

    paint(toMove, "green")

    changeText("cost", max(toMove))
    changeText("total", total + max(toMove))

    # Move to the Right
    movement(toMove, "right")

    total = total + currentCost

    # Move to the Left
    if len(toReturn) > 0:
        changeText("cost", min(toReturn))
        changeText("total", total)
        movement(toReturn, "left")
        changeText("cost", 0)


    if sum(nRight) == sum(persons):
        print("______COST______")
        print("COST: ", total)
    else:
        hillClimbing(persons, movement, paint, changeText, nRight, nLeft, total)

# hillClimbing([5, 10, 60, 70, 8, 4])

# f([5, 10, 60, 70, 8, 4])
